CREATE TABLE Players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Season TEXT NOT NULL,
  Team TEXT NOT NULL,
  Player TEXT NOT NULL,
);

CREATE TABLE PlayersForm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Season TEXT NOT NULL,
  Team TEXT NOT NULL,
  Player TEXT NOT NULL,
);